### ISSUE TITLE
Missing requirement: pandas

### ISSUE THREAD

**Issue by diije** [antoineeripret/gsc_wrapper#1]
Hello!
Thanks again for this lib ;)

Small issue: when trying to display the `ctr_yield_curve()` from a report, I get a `ModuleNotFoundError: No module named 'pandas'`.  

```
File "/.../gscwrapper/utils.py", line 88, in <module>  
    import pandas as pd 
```

I believe this would be fixed by including it to the lib requirements, or adding this step in the README instructions.    

Otherwise, you might want not to rely on a "heavy" library such as Pandas but that's probably a more difficult fix 😂

**Comment by diije** [comment]
I also had to install `tqdm`: there might be other missing requirements as well.

**Comment by antoineeripret** [comment]
Hey @diije, 

Thanks! 

Regarding the issue, thanks for raising it: it's an easy fix. Did you use the `requirements.txt` file to install dependencies, or just rely on the dependencies installed automatically by the library when it is imported? 

To be honest, I've assumed that Pandas would be installed, but it was indeed a mistake. 

Thanks !

**Comment by diije** [comment]
Hey @antoineeripret !

When installing a package with `pip`, the end user does not use the `requirements.txt`: if a dependency isn't specified as such in the project config (`setup.py` in this case), it won't be installed 😬 

I had a quick glance at the code, and spotted some other missing dependencies as well: numpy, prophet, causalimpact, requests. There might be more ;)

**Comment by antoineeripret** [comment]
@diije: 

Fair enough. 

I've updated the `setup.py` accordingly based on the missing dependencies I used: **pandas, numpy, requests, prophet and pycausalimpact**

Do not hesitate to open the issue again if you still have missing dependencies :)
