### ISSUE TITLE
Warning when using `group_data_by_period()`

### ISSUE THREAD

**Issue by diije** [antoineeripret/gsc_wrapper#13]
Hi there!

When using the `report.group_data_by_period()` method with a monthly group by, I get the following notice:

```
/python3.12/site-packages/gscwrapper/query.py:367: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
```

I'm guessing a minor change is coming to Pandas ;)

**Comment by antoineeripret** [comment]
Hi @diije, 

Thank you for your report! 

I've updated the accepted values for this method some weeks ago: 

```python 
#this is not from the API but we'll use it to group data by period
PERIODS = ['D','W','M','Q','Y','QE','ME']
```

I'll let it like this for now and force the `ME` and `QE` later on. I'll leave the issue opened until I push the update with this (little) change. 

Thank you !

**Comment by antoineeripret** [comment]
@diije : fixed.
