### ISSUE TITLE
OOB Migration

### ISSUE THREAD

**Issue by antoineeripret** [antoineeripret/gsc_wrapper#7]
(received in LI) 

Hey Antoine! I've been trying your GSC API app which used to work but now doesn't

The login flow returns this error.

![image](https://github.com/antoineeripret/gsc_wrapper/assets/9512616/c7774ead-ccb8-440b-bc6c-ac72437fcbb7)

which can be fixed by changing to redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F

This is Google docs: https://developers.google.com/identity/protocols/oauth2/resources/oob-migration

**Comment by jcchouinard** [comment]
import gscwrapper
import os 

def authenticate(config='gsc_client_secrets.json', token='gsc_credentials.json'):
    """Function to Authenticate GSC
    This will use existing credentials or ask you to authenticate
    'gsc_client_secrets.json': Credentials coming from Google Cloud Console
    'gsc_credentials.json': output where to store the token
    """
    if os.path.isfile(token):
        account = gscwrapper.generate_auth(config, credentials=token)
    else:
        account = gscwrapper.generate_auth(config, serialize=token)     
    return account

# Authenticate
account = authenticate()

# List Validated Properties
account.list_webproperties().head(2)

**Comment by jcchouinard** [comment]
I fixed this by using flow='web'  parameter.  account = gscwrapper.generate_auth(config, serialize=token, flow='web')

**Comment by antoineeripret** [comment]
@jcchouinard : fixed in last commit. Thanks !
